### ISSUE TITLE
Not easy to configure "single-shot" running

### ISSUE THREAD

**Issue by stuartlangridge** [Microsoft/ghcrawler-dashboard#25]
The existing crawler is rather designed to be able to scale to crawling many hundreds or thousands of repositories; it's a daemon which carefully schedules its work, and a separate set of utilities to control that daemon and add to its queues and so on. This is great if you _want_ to crawl thousands of repositories. It's pretty serious overkill if you want to crawl, say, three repositories though. Is there some way to run all this in "cut down" mode, where it wakes up and scans a repository and then shuts down, without needing lots of setup and a running background daemon and so on, so it's a bit less heavyweight? (The answer may be "no, that's not what it's designed for", which is fine, but if there's some way to spin it up in a lightweight way that would be useful to know about.)

**Comment by geneh** [comment]
Correct, that's not what it's designed for.
However, it is possible to bring ghcrawler up in memory or using Docker as described in ghcrawler project's [documentation](https://github.com/Microsoft/ghcrawler).
ghcrawler project also has detailed [wiki pages](https://github.com/Microsoft/ghcrawler/wiki).
Closing this issue since the question is related to another project.
